apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: urlshortener
    app: urlshortener
  name: urlshortener-metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      port: 9110
      protocol: TCP
      targetPort: 9110
  selector:
    control-plane: urlshortener
