---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - urlshortener.cedi.dev
  resources:
  - redirects
  - shortlinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener.cedi.dev
  resources:
  - redirects/finalizers
  - shortlinks/finalizers
  verbs:
  - update
- apiGroups:
  - urlshortener.cedi.dev
  resources:
  - redirects/status
  - shortlinks/status
  verbs:
  - get
  - patch
  - update
