apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: urlshortener-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: urlshortener-role
subjects:
  - kind: ServiceAccount
    name: urlshortener
    namespace: system
