# This rule is not used by the project 2025w24 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over urlshortener.cedi.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: 2025w24
    app.kubernetes.io/managed-by: kustomize
  name: shortlink-admin-role
rules:
- apiGroups:
  - urlshortener.cedi.dev
  resources:
  - shortlinks
  verbs:
  - '*'
- apiGroups:
  - urlshortener.cedi.dev
  resources:
  - shortlinks/status
  verbs:
  - get
