apiVersion: urlshortener.av0.de/v1alpha1
kind: Redirect
metadata:
  name: redirect-to-shortlink
spec:
  source: dev.ccl.pw
  target: short.av0.de
  code: 308
  tls:
    enable: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

---
apiVersion: urlshortener.av0.de/v1alpha1
kind: Redirect
metadata:
  name: redirect-example
spec:
  source: redirect.av0.de
  target: cedi.dev
  code: 302
