apiVersion: urlshortener.av0.de/v1alpha1
kind: ShortLink
metadata:
  name: shortlink-sample
spec:
  alias: "foobar"
  target: "https://openfaas.cedi.dev/function/cows"
  after: 5
---
apiVersion: urlshortener.av0.de/v1alpha1
kind: ShortLink
metadata:
  name: shortlink-sample2
spec:
  alias: "foobar2342"
  target: "https://openfaas.cedi.dev/function/cows"
  after: 5
---
apiVersion: urlshortener.av0.de/v1alpha1
kind: ShortLink
metadata:
  name: shortlink-sample3
spec:
  alias: "foobar2342"
  target: "https://openfaas.cedi.dev/function/cows"
  after: 5
