apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- urlshortener.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - urlshortener_config.yaml
  name: urlshortener-config
images:
- name: controller
  newName: ghcr.io/av0de/urlshortener
  newTag: develop
