basePath: /
info:
  contact:
    email: urlshortener@cedi.dev
    name: Cedric Kienzler
    url: cedi.dev
  description: A url shortener, written in Go running on Kubernetes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: URL Shortener
  version: "1.0"
paths:
  /{shortlink}:
    get:
      description: redirect to target as per configuration of the shortlink
      parameters:
      - description: shortlink id
        in: path
        name: shortlink
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: Success
          schema:
            type: integer
        "300":
          description: MultipleChoices
          schema:
            type: integer
        "301":
          description: MovedPermanently
          schema:
            type: integer
        "302":
          description: Found
          schema:
            type: integer
        "303":
          description: SeeOther
          schema:
            type: integer
        "304":
          description: NotModified
          schema:
            type: integer
        "305":
          description: UseProxy
          schema:
            type: integer
        "307":
          description: TemporaryRedirect
          schema:
            type: integer
        "308":
          description: PermanentRedirect
          schema:
            type: integer
        "404":
          description: NotFound
          schema:
            type: integer
        "500":
          description: InternalServerError
          schema:
            type: integer
      summary: redirect to target
      tags:
      - default
swagger: "2.0"
